### ISSUE TITLE
Fail to run 'SHOW DATABASES' with SQL alchemy

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/timeplus-connect#15]
Error message while integrating marimo with SQL alchemy

```
[W 250403 21:27:43 sqlalchemy:246] Failed to get schema names
    Traceback (most recent call last):
      File "/Users/jove/Dev/py312-env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
        meth = statement._execute_on_connection
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute '_execute_on_connection'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/jove/Dev/marimo/marimo/_sql/engines/sqlalchemy.py", line 244, in _get_schemas
        schema_names = self.inspector.get_schema_names()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jove/Dev/py312-env/lib/python3.12/site-packages/sqlalchemy/engine/reflection.py", line 363, in get_schema_names
        return self.dialect.get_schema_names(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jove/Dev/py312-env/lib/python3.12/site-packages/timeplus_connect/cc_sqlalchemy/dialect.py", line 45, in get_schema_names
        return [row.name for row in connection.execute('SHOW DATABASES')]
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/jove/Dev/py312-env/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
        raise exc.ObjectNotExecutableError(statement) from err
    sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'SHOW DATABASES'
```

**Comment by jovezhong** [comment]
No such effort in marimo console after upgrade to 0.8.16, although running `SHOW DATABASES` cell will fall back to a command, not a query
```
        raise _ConvertError(f"Invalid type {type(value)}")
    tomlkit.items._ConvertError: Invalid type <class 'NoneType'>
'SHOW DATABASES
    ' contains unsupported syntax. Falling back to parsing as a 'Command'.
```
